### PR TITLE
DEMO-89: As a user, I want to be able to configure server and credentials

### PR DESCRIPTION
**Pull request by clash82**
https://jira.ez.no/browse/DEMO-89

screen shot 2017-02-23 at 14 12 09

### CODE REVIEW

**Comment by clash82** [comment]
review please @SylvainGuittard

**Comment by clash82** [comment]
updated @SylvainGuittard

**Comment by clash82** [comment]
SVG image added, final review please @SylvainGuittard

**Review by SylvainGuittard — APPROVED** [review]
Thanks @clash82 
Good job!

**Pull request merged**
